<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="bunit.web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Weather.Web\Weather.Web.csproj" />
  </ItemGroup>

</Project>
